import fs from 'node:fs/promises'; import path from 'node:path'; import {pathToFileURL} from 'node:url'; import {Presentation,PresentationFile} from '@oai/artifact-tool';
const SKILL_DIR='/Users/mjm/.codex/plugins/cache/openai-primary-runtime/presentations/26.909.12148/skills/presentations'; const workspaceDir='/Users/mjm/Papers/Qingsong/IJCAI2027-Time-Series-Agents-Survey'; const buildDir=path.join(workspaceDir,'.ppt-build'); const finalName=process.env.SUPPORT_OUT||'Figure_supporting_workflows_native_notitle.pptx'; const finalPath=path.join(workspaceDir,'artifacts','active',finalName);
const {resolvePresentationFont,finalizePresentation}=await import(pathToFileURL(path.join(SKILL_DIR,'container_tools/artifact_tool_utils.mjs')).href); const family=resolvePresentationFont({fontFamily:'Times New Roman'}); const p=Presentation.create({slideSize:{width:1280,height:720}});
const C={navy:'#24324A',ink:'#303A4B',muted:'#687386',line:'#667085',blue:'#D9EEF0',teal:'#438B86',green:'#DDEEDC',yellow:'#F4F0C9',gold:'#B77F2B',purple:'#E6E0F2',violet:'#78639F',red:'#F3E2DE',salmon:'#B86659',white:'#FFFFFF'};
function txt(s,x,y,w,h,t,z=18,col=C.ink,b=false,it=false,a='center'){const q=s.shapes.add({geometry:'textbox',position:{left:x,top:y,width:w,height:h},fill:'none',line:{style:'solid',fill:'none',width:0}});q.text=t;q.text.style={typeface:family,fontSize:z,color:col,bold:b,italic:it,align:a,verticalAlign:'mid',autoFit:'shrink'};return q}
function box(s,x,y,w,h,fill,line=C.line,opts={}){const g=opts.geometry||'roundRect';const c={geometry:g,position:{left:x,top:y,width:w,height:h},fill,line:{style:opts.dash?'dashed':'solid',fill:line,width:opts.lw||1.4}};if(g==='roundRect'||g==='rect'||g==='textbox')c.borderRadius='rounded-lg';return s.shapes.add(c)}
function conn(s,a,b,col=C.line,dash=false){return s.shapes.connect(a,b,{kind:'straight',fromSide:'right',toSide:'left',line:{style:dash?'dashed':'solid',fill:col,width:2},head:{type:'arrow',width:'sm',length:'sm'}})}
function title(s,t,sub){ if(process.env.NO_TITLE==='1') return; txt(s,50,24,1180,40,t,32,C.navy,true);txt(s,50,68,1180,25,sub,15,C.muted,false,true,'left')}
function card(s,x,y,w,h,head,body,fill,line){const b=box(s,x,y,w,h,fill,line,{lw:1.4});txt(s,x+10,y+10,w-20,28,head,17,line,true);txt(s,x+12,y+42,w-24,h-50,body,12,C.ink,false);return b}
function note(s,src){s.speakerNotes.textFrame.setText(`Redrawn schematic adapted from ${src}. Labels and geometry are normalized for this survey; the original paper remains the source of the mechanism.`)}
// ChatTS
{const s=p.slides.add();s.background.fill='#fff';title(s,'Temporal alignment and instruction data','LLM-side contribution: numerical series enter language-model training through two complementary data paths.');const a=card(s,70,280,180,72,'Attribute selector','selects temporal attributes',C.blue,C.teal);const b=card(s,340,175,230,100,'Attribute-based generator','generates series with selected attributes',C.yellow,C.gold);const c=card(s,340,390,230,100,'Time-series evol-instruct','generates temporal instruction text',C.purple,C.violet);const d=card(s,690,280,220,100,'Generated training data','series + language supervision',C.green,C.teal);const e=card(s,1030,280,170,100,'Model training','temporal alignment',C.blue,C.teal);conn(s,a,b,C.teal);conn(s,a,c,C.violet);conn(s,b,d,C.gold);conn(s,c,d,C.violet);conn(s,d,e,C.teal);txt(s,300,130,650,30,'model-side representation and reasoning',16,C.navy,true,false,'center');note(s,'ChatTS, Fig. 3');}
// AION
{const s=p.slides.add();s.background.fill='#fff';title(s,'Three principles for a reliable time-series Agent','The temporal contract couples grounding, knowledge use, and reliability checks.');const cols=[['Temporal grounding',['Task specification','Data interface','Visual analysis'],C.blue,C.teal],['Knowledge-grounded reasoning',['Strong knowledge dependence','Temporal hypothesis expansion','Rules-aware reasoning'],C.green,C.teal],['Reliability mechanisms',['Post-experiment analysis','Event-aware reasoning','Layered review'],C.yellow,C.gold]];const principleBoxes=[];cols.forEach((c,i)=>{const x=70+i*390;const panel=box(s,x,150,340,420,c[2],c[3],{lw:1.5});principleBoxes.push(panel);txt(s,x+15,170,310,34,c[0],20,c[3],true);c[1].forEach((t,j)=>{box(s,x+30,235+j*90,280,62,C.white,c[3],{lw:1});txt(s,x+42,244+j*90,256,22,t,14,C.ink,true);txt(s,x+42,270+j*90,256,18,j===0?'declares the task contract':'adds an inspectable check',10,C.muted,false);});});conn(s,principleBoxes[0],principleBoxes[1],C.teal);conn(s,principleBoxes[1],principleBoxes[2],C.gold);note(s,'AION, Fig. 2');}
// MERIT
{const s=p.slides.add();s.background.fill='#fff';title(s,'Retrieval, augmentation, and review','A task-specific synthesis loop couples candidate generation to fidelity and utility checks.');const a=card(s,80,250,230,105,'Retrieval agent','finds similar temporal samples',C.blue,C.teal);const b=card(s,405,250,230,105,'Augmentation agent','generates a conditioned sample',C.green,C.teal);const c=card(s,730,250,230,105,'Review agent','checks fidelity and utility',C.yellow,C.gold);const d=card(s,1015,250,170,105,'Accepted set','keeps usable data',C.purple,C.violet);conn(s,a,b,C.teal);conn(s,b,c,C.gold);conn(s,c,d,C.violet);conn(s,c,a,C.red,true);txt(s,170,160,930,36,'retrieval  →  generation  →  review  →  downstream use',19,C.navy,true);txt(s,95,420,1070,40,'Temporal fidelity: dependence, missingness, distribution  |  Utility: downstream task performance',14,C.muted,false,'center');note(s,'MERIT, Fig. 2');}
// AnomaMind
{const s=p.slides.add();s.background.fill='#fff';title(s,'Coarse-to-fine anomaly diagnosis','Evidence acquisition and iterative refinement connect detection to a diagnosis and a final alert.');const labels=[['Evidence acquisition','retrieve signals and context',C.blue,C.teal],['Evidence construction','align and summarize evidence',C.green,C.teal],['Anomaly detection','score candidate events',C.yellow,C.gold],['Diagnosis','identify cause and confidence',C.red,C.salmon]];const diagnosisBoxes=[];labels.forEach((r,i)=>{const x=60+i*290;diagnosisBoxes.push(card(s,x,260,240,115,r[0],r[1],r[2],r[3]));});for(let i=0;i<3;i++)conn(s,diagnosisBoxes[i],diagnosisBoxes[i+1],labels[i][3]);box(s,130,150,1020,60,C.purple,C.violet,{dash:true,lw:1.2});txt(s,150,162,980,30,'training and feedback update the detector, diagnostic tools, and review policy',16,C.violet,true);box(s,170,455,900,70,C.white,C.navy,{lw:1.3});txt(s,195,470,850,25,'toolkit: time-series memory · numerical diagnostics · event labels · evaluator',14,C.navy,true);note(s,'AnomaMind, Fig. 1');}
// TimeClaw
{const s=p.slides.add();s.background.fill='#fff';title(s,'A time-series-native runtime','Numerical execution, capability evolution, and multimodal memory remain connected through auditable trajectories.');const a=card(s,60,260,220,120,'Contextual series','values, events, metadata',C.blue,C.teal);const b=card(s,360,230,250,170,'Time-series runtime','server-side numerical execution\nstate and tools',C.green,C.teal);const c=card(s,695,230,250,170,'Capability evolution','evaluate, update, retain, release',C.yellow,C.gold);const d=card(s,1030,260,190,120,'Multimodal memory','retrieve and reuse',C.purple,C.violet);conn(s,a,b,C.teal);conn(s,b,c,C.gold);conn(s,c,d,C.violet);conn(s,d,b,C.violet,true);txt(s,320,150,650,32,'auditable trajectories close the loop',18,C.navy,true);note(s,'TIMECLAW, Fig. 2');}
// TimeSeriesGym
{const s=p.slides.add();s.background.fill='#fff';title(s,'Benchmark infrastructure for executable agents','A benchmark combines heterogeneous sources, ML-engineering challenges, skill simulators, graders, and multimodal outputs.');const a=card(s,60,250,220,140,'Multiple sources','Kaggle · GitHub · data resources',C.blue,C.teal);const b=card(s,360,220,240,200,'Challenges','descriptions · resources\nskill simulators · code improvement',C.purple,C.violet);const c=card(s,680,250,200,140,'Agent-agnostic design','same contract for different Agents',C.yellow,C.gold);const d=card(s,960,180,220,90,'Quantitative grader','accuracy, error, runtime',C.green,C.teal);const e=card(s,960,350,220,90,'Qualitative grader','trace and artifact review',C.green,C.teal);conn(s,a,b,C.teal);conn(s,b,c,C.violet);conn(s,c,d,C.gold);conn(s,c,e,C.gold);txt(s,925,500,280,40,'multimodal outputs\nfiles · models · code',15,C.navy,true);note(s,'TimeSeriesGym, Fig. 1');}
// TS-Agent
{const s=p.slides.add();s.background.fill='#fff';title(s,'Tool-using temporal reasoning trace','A General Harness loop exposes evidence, tool calls, critique, and a verified answer.');const a=card(s,55,260,170,110,'Time-series data','observations',C.blue,C.teal);const b=card(s,280,260,170,110,'Evidence log','provenance',C.green,C.teal);const c=card(s,505,230,240,170,'Temporal tools','trend · anomaly\ncorrelation · forecast',C.yellow,C.gold);const d=card(s,800,260,170,110,'LLM critic','check and revise',C.purple,C.violet);const e=card(s,1025,260,170,110,'Final answer','evidence-backed',C.red,C.salmon);conn(s,a,b,C.teal);conn(s,b,c,C.teal);conn(s,c,d,C.gold);conn(s,d,e,C.violet);conn(s,d,b,C.violet,true);txt(s,230,150,750,32,'observe  →  execute  →  critique  →  verify',19,C.navy,true);note(s,'TS-Agent, Fig. 3');}
await fs.mkdir(path.dirname(finalPath),{recursive:true}); const candidate=path.join(buildDir,'candidate-redrawn-workflows.pptx'); await (await PresentationFile.exportPptx(p)).save(candidate); for(let i=0;i<p.slides.items.length;i++){const b=await p.export({slide:p.slides.items[i],format:'png',scale:2});await fs.writeFile(path.join(buildDir,`redrawn-${i+1}.png`),new Uint8Array(await b.arrayBuffer()));}
const res=await finalizePresentation({workspaceDir,candidatePath:candidate,finalPath,pythonExecutable:'/Users/mjm/.cache/codex-runtimes/codex-primary-runtime/dependencies/python/bin/python3',integrityValidatorPath:path.join(SKILL_DIR,'container_tools/inspect_presentation_package_integrity.py'),layoutValidatorPath:path.join(SKILL_DIR,'container_tools/inspect_presentation_layout_geometry.py'),layoutArgs:['--expected-slide-size-emu','12192000,6858000','--validate-heading-fit'],fontPolicy:{basis:'user_request',families:['Times New Roman']},verifyArtifactToolImport:true,receiptPath:path.join(buildDir,'supporting-workflows.validation.json')});console.log(JSON.stringify(res));
