import fs from 'node:fs/promises';
import path from 'node:path';
import {pathToFileURL} from 'node:url';
import {Presentation,PresentationFile} from '@oai/artifact-tool';
const SKILL_DIR='/Users/mjm/.codex/plugins/cache/openai-primary-runtime/presentations/26.909.12148/skills/presentations';
const workspaceDir='/Users/mjm/Papers/Qingsong/IJCAI2027-Time-Series-Agents-Survey';
const buildDir=path.join(workspaceDir,'.ppt-build');
const finalPath=path.join(workspaceDir,'artifacts','RSI_Reference_Figures_Editable_TNR.pptx');
const {resolvePresentationFont,finalizePresentation}=await import(pathToFileURL(path.join(SKILL_DIR,'container_tools/artifact_tool_utils.mjs')).href);
const family=resolvePresentationFont({fontFamily:'Times New Roman'});
const p=Presentation.create({slideSize:{width:1280,height:720}});
const C={ink:'#20242B',muted:'#687078',line:'#45505A',blue:'#DCEFF1',teal:'#4F8F89',green:'#E1EEDC',green2:'#6B9F80',yellow:'#F5F0CE',gold:'#B47B24',purple:'#E8E0F0',violet:'#6D6396',red:'#F4DFDD',salmon:'#B9675E',white:'#FFFFFF',gray:'#F4F5F4',dark:'#33434A'};
function t(s,x,y,w,h,text,size=16,color=C.ink,bold=false,italic=false,align='left'){const q=s.shapes.add({geometry:'textbox',position:{left:x,top:y,width:w,height:h},fill:'none',line:{style:'solid',fill:'none',width:0}});q.text=text;q.text.style={typeface:family,fontSize:size,color,bold,italic,align,verticalAlign:'mid',autoFit:'shrink'};return q}
function b(s,x,y,w,h,fill=C.white,line=C.line,opts={}){const g=opts.geometry||'roundRect';return s.shapes.add({geometry:g,position:{left:x,top:y,width:w,height:h},fill,line:{style:opts.dash?'dashed':'solid',fill:line,width:opts.lw??1.2}})}
function line(s,x,y,w,h,color=C.line){return b(s,x,y,w,h,color,color,{geometry:'rect',lw:0})}
function conn(s,a,bx,color=C.line,dash=false){return s.shapes.connect(a,bx,{kind:'straight',fromSide:'right',toSide:'left',line:{style:dash?'dashed':'solid',fill:color,width:1.8},head:{type:'arrow',width:'sm',length:'sm'}})}
function title(s,head,sub=''){t(s,44,22,1190,40,head,30,C.ink,true);if(sub)t(s,46,60,1190,24,sub,14,C.muted,false,true)}
function note(s,src){s.speakerNotes.textFrame.setText(`Editable reconstruction based on the user-provided RSI reference screenshot: ${src}. This slide uses native PowerPoint text, shapes, lines, and connectors; it is a visual study, not the source figure.`)}
function dot(s,x,y,r,fill){return b(s,x-r,y-r,2*r,2*r,fill,fill,{geometry:'ellipse',lw:0})}
function arrowDown(s,x,y,h,color=C.line){line(s,x,y,2,h,color);b(s,x-6,y+h-2,14,8,color,color,{geometry:'triangle',lw:0})}
// 1 module-level log chart
{const s=p.slides.add();s.background.fill=C.white;title(s,'Module-level contributions across the reviewed corpus','Cumulative module counts on a logarithmic scale');const x=100,y=170,w=1040,h=390;line(s,x,y+h,w,2,C.line);line(s,x,y,2,h,C.line);[1,10,100].forEach((v,i)=>{const yy=y+h-i*145;line(s,x-8,yy,8,1,C.line);t(s,45,yy-12,45,22,String(v),12,C.muted,false,false,'right')});['Oct 2023','Feb 2024','Jun 2024','Oct 2024','Feb 2025','Jun 2025','Oct 2025','Feb 2026','Jun 2026'].forEach((v,i)=>t(s,x+i*(w/8)-35,y+h+16,75,22,v,9,C.muted,false,false,'center'));
 const series=[{name:'General Time-Series Harness',color:C.gold,pts:[[0,.02],[1,.02],[2,.02],[3,.10],[4,.10],[5,.22],[6,.30],[7,.37],[8,.48]]},{name:'Task-Specific Harness',color:C.green2,pts:[[0,.02],[1,.30],[2,.34],[3,.37],[4,.48],[5,.55],[6,.64],[7,.72],[8,.82]]},{name:'LLM-side',color:C.violet,pts:[[0,.02],[1,.15],[2,.15],[3,.15],[4,.25],[5,.25],[6,.25],[7,.25],[8,.25]]},{name:'General Harness',color:'#4D7896',pts:[[0,.02],[1,.02],[2,.02],[3,.38],[4,.45],[5,.52],[6,.62],[7,.72],[8,.78]]}];
 series.forEach((se,k)=>{const nodes=[];se.pts.forEach(([i,v])=>nodes.push(dot(s,x+i*(w/8),y+h-v*h,5,se.color)));for(let i=0;i<nodes.length-1;i++)conn(s,nodes[i],nodes[i+1],se.color);const ly=90+k*22;line(s,820,ly+8,24,3,se.color);t(s,850,ly,245,22,se.name,12,C.ink,false)});t(s,120,112,540,24,'Cumulative module contributions (log scale)',14,C.ink,true);t(s,120,590,1000,35,'Figure-style reconstruction: counts are recorded at the module level, so one paper may contribute to multiple curves.',12,C.muted,false,true);note(s,'03514d1b-0ebc-4946-8261-3b775509d1f7.png')}
// 2 organization
{const s=p.slides.add();s.background.fill=C.white;title(s,'Organization of the survey','Sections follow the construction of a system and the evidence used to evaluate it.');const spine=line(s,126,124,4,500,C.line);const rows=[['§ 1','Introduction','Scope, motivation, and central questions',C.yellow,C.gold],['§ 2','Scope and Review Methodology','Inclusion and evidence-led review',C.yellow,C.gold],['§ 3','Foundations and Problem Formulation','Agent, LLM, and time-series layers',C.purple,C.violet],['§ 4','Taxonomy of Time-Series Agents','Reusable modules and task contracts',C.blue,C.teal],['§ 5','Automated Design and Infrastructure','Tools, memory, and execution',C.green,C.green2],['§ 6','Repair and Experimentation','Trace, revision, and validation',C.green,C.green2],['§ 7','Benchmarks and Evaluation','Goal-matched tests and reports',C.blue,C.teal],['§ 8','Challenges and Future Directions','Open problems and coverage gaps',C.purple,C.violet],['§ 9','Conclusion','Open limits and next tests',C.purple,C.violet]];rows.forEach((r,i)=>{const yy=120+i*53;dot(s,126,yy+24,6,r[4]);b(s,155,yy,300,43,r[3],r[4],{dash:true});t(s,170,yy+8,34,26,r[0],12,r[4],true);t(s,210,yy+5,230,20,r[1],13,C.ink,true);b(s,480,yy,330,43,C.white,C.line,{lw:1});t(s,495,yy+7,300,28,r[2],12,C.ink,false)});b(s,65,120,50,290,C.blue,C.teal,{dash:true});t(s,74,185,32,100,'RSI\nSurvey',16,C.teal,true,false,'center');b(s,65,645,745,32,C.white,C.line,{lw:1});t(s,80,651,715,20,'Paper-card fields: claim · evidence locator · module layer · task family · BibTeX · review status',11,C.ink,false);note(s,'250411b2-1d1f-4bba-a7bd-241fd0ec6be1.png')}
// 3 landscape
{const s=p.slides.add();s.background.fill=C.white;title(s,'The landscape of recursive self-improvement','Mechanisms, evaluation evidence, and improvement objectives occupy different layers.');b(s,420,130,420,420,C.gray,C.line,{geometry:'ellipse',lw:1.5});const center=dot(s,630,340,8,C.line);for(let i=0;i<8;i++){const ang=-1.3+i*.37;const x=630+Math.cos(ang)*250;const y=340+Math.sin(ang)*210;const endpoint=dot(s,x,y,4,C.line);conn(s,center,endpoint,C.line,false)};['Representation','Improvement mechanism','Evaluation','Data / feedback'].forEach((v,i)=>{const x=470+i*175;b(s,x,120,150,35,[C.blue,C.green,C.yellow,C.purple][i],[C.teal,C.green2,C.gold,C.violet]);t(s,x+6,127,138,20,v,11,C.ink,true,false,'center')});['LLM','Memory','Tools','Policy','Planner','Verifier','Benchmarks','Deployment'].forEach((v,i)=>{const a=-1.25+i*.35;const x=610+Math.cos(a)*190;const y=328+Math.sin(a)*155;dot(s,x,y,12,[C.teal,C.violet,C.gold,C.salmon][i%4]);t(s,x-40,y+15,80,18,v,9,C.ink,false,false,'center')});b(s,120,595,1010,36,C.white,C.line,{lw:1});t(s,145,603,960,20,'Interpreted outputs: module maps, evaluation evidence, and research routes toward improvement.',12,C.ink,true,false,'center');note(s,'2ee58a4a-5ea6-43c1-b6cd-fa97801e2762.png')}
// 4 six-panel open problems
{const s=p.slides.add();s.background.fill=C.white;title(s,'Open problems for recursive improvement','Bottleneck  →  research question  →  targeted probe');const panels=[['(a) Feedback','Judge bias / weak signals','External checks + judge calibration',C.yellow,C.gold],['(b) Experience','Diversity / retention','Replay mix + retention under shift',C.green,C.green2],['(c) Stability','Regression across rounds','Long-run replay + rollback ablation',C.blue,C.teal],['(d) Integrity','Contamination / gaming','Sealed tasks + protected evaluator',C.yellow,C.gold],['(e) Compute','Search and checking cost','Allocation sweep at fixed total cost',C.green,C.green2],['(f) Transfer','Task gain ≠ improver gain','Same starting solver across new domains',C.blue,C.violet]];panels.forEach((pnl,i)=>{const x=35+(i%3)*405,y=115+Math.floor(i/3)*285;b(s,x,y,370,255,pnl[3],C.line,{dash:true,lw:1.5});t(s,x+18,y+12,330,30,pnl[0],22,C.ink,true);t(s,x+20,y+50,330,24,pnl[1],14,C.muted,true,true);b(s,x+65,y+92,240,52,C.white,pnl[4],{lw:1});t(s,x+80,y+108,210,22,'mechanism sketch',13,pnl[4],true,false,'center');arrowDown(s,x+184,y+154,40,pnl[4]);t(s,x+28,y+205,314,37,pnl[2],13,pnl[4],true,false,'center')});note(s,'473be8a2-e4eb-4cca-bfdd-97302b50480b.png')}
// 5 coverage table
{const s=p.slides.add();s.background.fill=C.white;title(s,'Coverage of survey-relevant dimensions','Survey rows and evaluation columns use the same compact check vocabulary.');const x0=60,y0=125;const cols=['Survey','System\nboundary','Recursive\nagency','Evaluation\nevidence','Open\nloop','Pair'];const widths=[260,125,125,165,100,80];let xx=x0;cols.forEach((c,i)=>{b(s,xx,y0,widths[i],58,C.blue,C.line,{lw:1});t(s,xx+4,y0+8,widths[i]-8,42,c,12,C.ink,true,false,'center');xx+=widths[i]});const names=['General RSI survey','Agentic forecasting survey','TS Agent survey','Harness survey','This survey'];names.forEach((name,r)=>{let xx=x0;const yy=y0+58+r*53;b(s,xx,yy,widths[0],53,r===4?C.green:C.white,C.line,{lw:1});t(s,xx+10,yy+14,widths[0]-20,22,name,12,C.ink,r===4);xx+=widths[0];for(let c=1;c<cols.length;c++){b(s,xx,yy,widths[c],53,r===4?C.green:C.gray,C.line,{lw:1});t(s,xx,yy+10,widths[c],30,(r+c)%3===0?'✓':(r+c)%3===1?'△': '—',12,(r+c)%3===0?C.green2:(r+c)%3===1?C.gold:C.muted,true,false,'center');xx+=widths[c]}});t(s,60,500,1060,48,'✓ reported   △ partial   — not explicit. The comparison is descriptive and follows the source survey’s stated scope.',12,C.muted,false,true);note(s,'70181ba7-3a8e-4452-9f50-ffa240cc6655.png')}
// 6 four perspectives
{const s=p.slides.add();s.background.fill=C.white;title(s,'Four perspectives on recursive improvement','Each perspective highlights a distinct object of change.');const ps=[['Answer','what will be checked?',C.yellow,C.gold],['Memory','what remains available?',C.blue,C.teal],['Parameters','what is learned?',C.green,C.green2],['Improver','what proposes change?',C.purple,C.violet]];ps.forEach((pnl,i)=>{const x=55+i*295;b(s,x,140,250,250,pnl[2],pnl[3],{dash:true});t(s,x+15,158,220,28,pnl[0],20,C.ink,true,false,'center');b(s,x+35,205,180,70,C.white,pnl[3],{lw:1});t(s,x+45,226,160,25,'native components',13,pnl[3],true,false,'center');t(s,x+22,295,206,22,pnl[1],12,C.muted,true,true,'center');b(s,x+20,415,210,100,C.white,C.line,{lw:1});t(s,x+32,435,186,55,['check → revise','retain → retrieve','fit → update','propose → select'][i],14,C.ink,true,false,'center')});line(s,120,565,1040,2,C.line);t(s,190,585,900,25,'Local checking and memory are coupled by a retained state; the improver closes the loop.',14,C.ink,true,false,'center');note(s,'7572f4b2-a5e3-4239-800f-b94ac30e4317.png')}
// 7 recursive loop
{const s=p.slides.add();s.background.fill=C.white;title(s,'Recursive self-improvement','A mechanism-level view of task systems, experience, candidate changes, and validation.');const nodes=[['Task systems $T_0$','model, data,\nknown tools',75,150,C.blue,C.teal],['Experiences','traces, outcomes,\nfeedback',390,150,C.green,C.green2],['Updated systems $T_{i+1}$','accepted state\nand tools',705,150,C.blue,C.teal],['Improvement process $I_i$','diagnose, search,\npropose',75,420,C.purple,C.violet],['Candidate changes','proposals, tests,\ncomparisons',390,420,C.yellow,C.gold],['Validate & select','gain, regression,\nresource bounds',705,420,C.green,C.green2]];const sh=[];nodes.forEach(n=>{const q=b(s,n[2],n[3],230,125,n[4],n[5],{lw:1.3});sh.push(q);t(s,n[2]+15,n[3]+16,200,24,n[0],16,C.ink,true,false,'center');t(s,n[2]+20,n[3]+55,190,40,n[1],12,C.ink,false,false,'center')});conn(s,sh[0],sh[1],C.teal);conn(s,sh[1],sh[2],C.teal);conn(s,sh[2],sh[5],C.green2);conn(s,sh[5],sh[4],C.gold);conn(s,sh[4],sh[3],C.violet);conn(s,sh[3],sh[0],C.violet);t(s,250,300,780,35,'execute  →  learn  →  propose  →  validate  →  update',17,C.ink,true,false,'center');note(s,'93b9b499-6e13-4dd0-bbe2-28235f020bfe.png')}
// 8 update mechanisms and evidence
{const s=p.slides.add();s.background.fill=C.white;title(s,'From update mechanisms to evaluation evidence','Selected, source-checked configurations; evidence coverage is not a method ranking.');b(s,40,115,585,500,C.yellow,C.line,{dash:true,lw:1.5});b(s,655,115,585,500,C.blue,C.line,{dash:true,lw:1.5});t(s,65,135,500,30,'(a) What is updated?',22,C.ink,true);t(s,680,135,500,30,'(b) What is tested?',22,C.ink,true);t(s,65,178,510,24,'20 works',16,C.muted,true,true);t(s,680,178,510,24,'8 works with protocol-level evidence',16,C.muted,true,true);const lh=['Data','Weights','Memory','Policy','Judge','Improver'];lh.forEach((v,i)=>{const x=280+i*42;t(s,x,215,38,65,v,11,C.ink,true,true,'center');line(s,x+16,235,2,320,[C.green2,C.green2,C.teal,C.violet,C.gold,C.salmon][i])});const names=['STaR','Self-Instruct','SPIN','Self-Rewarding','Meta-Rewarding','Absolute Zero','Reflexion','Voyager','Expel','OPRO','TextGrad','ADAS','GEPA','AlphaEvolve','Promptbreeder','STOP','SICA','DGM','Hyperagents','Metan'];names.forEach((n,i)=>{const y=250+i*16;t(s,75,y,180,16,n,10,C.ink,true);for(let j=0;j<6;j++){if((i+j)%3===0)dot(s,300+j*42,y+8,5,[C.green2,C.teal,C.violet,C.gold][j%4])}});['Held-out tests','Budget control','Improver transfer'].forEach((v,i)=>{const x=760+i*135;t(s,x,220,120,40,v,11,C.ink,true,false,'center');for(let r=0;r<8;r++){b(s,x,265+r*37,120,35,[C.green,C.yellow,C.purple][i],C.white,{lw:1});t(s,x,273+r*37,120,18,r%3===0?'✓':r%3===1?'NR':'△',16,r%3===0?C.green2:r%3===1?C.muted:C.gold,true,false,'center')}});t(s,75,590,1100,18,'Filled circles denote update objects; ✓ reported · △ qualified · NR not reported.',11,C.muted,false,true);note(s,'a5f5d981-2117-48b5-8cb6-bcbbbbe0f3e6.png')}
// 9 neighboring perspectives
{const s=p.slides.add();s.background.fill=C.white;title(s,'Perspectives on self-improvement','A cross-cutting synthesis from lifecycle, components, and recursive improvement.');const cards=[['Lifecycles and agents','What changes?\nWhen and where?',C.yellow,C.gold],['Components','How does it work?\nWhich state persists?',C.green,C.green2],['Recursive improvement','How is the loop closed?\nWhat evidence supports it?',C.blue,C.teal]];cards.forEach((r,i)=>{const x=110+i*365;b(s,x,170,320,160,r[2],r[3],{dash:true});t(s,x+15,190,290,28,r[0],19,C.ink,true,false,'center');t(s,x+25,240,270,55,r[1],14,C.ink,false,false,'center')});b(s,185,425,910,90,C.blue,C.teal,{lw:1.5});t(s,220,445,840,28,'This survey: a cross-cutting synthesis',19,C.ink,true,false,'center');t(s,220,480,840,22,'Engineering goal → testable question → tested redistribution',13,C.ink,false,false,'center');note(s,'cc759328-3690-4186-9986-fe51794f5931.png')}
// 10 research routes timeline
{const s=p.slides.add();s.background.fill=C.white;title(s,'Research routes toward recursive self-improvement','Method families by public year; placement is a map of routes, not a ranking.');const cols=[['Data &\nupdates',C.yellow,C.gold],['Models &\nfeedback',C.green,C.green2],['Memory &\nretrieval',C.blue,C.teal],['Code &\nplanning',C.purple,C.violet],['Evaluation &\njudges',C.red,C.salmon],['Multi-agent\nloops',C.blue,C.teal]];const xs=170, gap=150;cols.forEach((c,i)=>{const x=xs+i*gap;b(s,x,100,120,56,c[1],c[2],{lw:1});t(s,x+8,113,104,32,c[0],12,C.ink,true,false,'center');line(s,x+58,160,3,430,c[2]);['2023','2024','2025','2026'].forEach((y,j)=>{const yy=185+j*100;t(s,65,yy-8,80,20,y,12,C.muted,true,false,'right');const q=b(s,x+18,yy,84,32,c[1],c[2],{lw:1});t(s,x+22,yy+8,76,16,['T0','T1','T2','T3'][j],10,C.ink,true,false,'center')})});b(s,150,620,955,42,C.white,C.line,{lw:1});t(s,180,631,895,20,'Adjacent routes can contribute to the same evolving system; the map emphasizes module-level links.',12,C.ink,true,false,'center');note(s,'ded9e63e-c562-44fb-941d-7de354ae4c7d.png')}
// 11 text panel style
{const s=p.slides.add();s.background.fill='#171717';title(s,'Scenario-grounded temporal evidence','A compact text-panel style for concrete application contexts.');b(s,90,160,1100,395,'#171717','#F4F4F4',{lw:1.2});const items=[['气候','天气模式的变化可能预示着气候异常或长期变化。'],['行业','预测设备故障或维护需求的机械传感器读数的变化。'],['医疗健康','生理信号的突然变化可能表明健康风险。'],['财务','与风险管理和投资组合决策相关的市场或赔行为的转变。']];items.forEach((r,i)=>{const y=205+i*75;t(s,125,y,90,24,'• '+r[0]+'：',18,C.white,true);t(s,225,y,900,30,r[1],16,C.white,false)});note(s,'c4471a69-b143-4c54-8d60-2b3909aec7b0.png')}
await fs.mkdir(path.dirname(finalPath),{recursive:true});const candidate=path.join(buildDir,'candidate-rsi-reference-components.pptx');await (await PresentationFile.exportPptx(p)).save(candidate);for(let i=0;i<p.slides.items.length;i++){const blob=await p.export({slide:p.slides.items[i],format:'png',scale:2});await fs.writeFile(path.join(buildDir,`rsi-reference-${i+1}.png`),new Uint8Array(await blob.arrayBuffer()))};const res=await finalizePresentation({workspaceDir,candidatePath:candidate,finalPath,pythonExecutable:'/Users/mjm/.cache/codex-runtimes/codex-primary-runtime/dependencies/python/bin/python3',integrityValidatorPath:path.join(SKILL_DIR,'container_tools/inspect_presentation_package_integrity.py'),layoutValidatorPath:path.join(SKILL_DIR,'container_tools/inspect_presentation_layout_geometry.py'),layoutArgs:['--expected-slide-size-emu','12192000,6858000','--validate-heading-fit'],fontPolicy:{basis:'design',families:[family]},verifyArtifactToolImport:true,receiptPath:path.join(buildDir,'rsi-reference-components.validation.json')});console.log(JSON.stringify(res));
